namespace FontAwesome
{
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/matthewrdev/fa2cs).
    /// </summary>
    public static partial class FontAwesomeIcons
    {

        /// fa-chevron-down unicode value ("\uf078").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string BarsStaggered = "\uf550";
        public const string ChevronDown = "\uf078";

        /// fa-chevron-down unicode value ("\uf078").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string ChevronUp = "\uf077";

        /// fa-chevron-right unicode value ("\uf054").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string ChevronRight = "\uf054";

        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string Check = "\uf00c";

        public const string CheckCircle = "\uf058";
        public const string Clipboard = "\uf328";

        /// fa-filter unicode value ("\uf0b0").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string Filter = "\uf0b0";
        public const string Compass = "\uf14e";

        public const string User = "\uf007";

        public const string Bookmark = "\uf02e";

        /// fa-sort unicode value ("\uf0dc").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string Sort = "\uf0dc";
        public const string GrinBeam = "\uf582";
        public const string GrinHearts = "\uf584";
        public const string GrinStars = "\uf587";
        /// fa-heart unicode value ("\uf004").
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        public const string Heart = "\uf004";

        public const string RightArrowAlt = "\uf30b";

        /// fa-share-alt unicode value ("\uf1e0").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string Search = "\uf002";

        public const string ShareAlt = "\uf1e0";
        public const string StoreAlt = "\uf54f";
        public const string Smile = "\uf118";
        public const string SmileBeam = "\uf5b8";

        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string ShoppingBag = "\uf290";
        public const string ShoppingCart = "\uf07a";
        public const string Signature = "\uf5b7";

        /// fa-map-marker-alt unicode value ("\uf3c5").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string MapMarkerAlt = "\uf3c5";
        public const string Minus = "\uf068";

        /// fa-plus unicode value ("\uf067").
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid, Duotone (Pro)
        public const string Plus = "\uf067";

        public const string TimesCircle = "\uf057";
        public const string Tags = "\uf02c";

        /// fa-trash-alt unicode value ("\uf2ed").
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        public const string TrashAlt = "\uf2ed";
    }
}
